# additional data require to create the Docker image
packaging:
  add:
    - target/${project.build.finalName}.war
#ports will forward the container to localhost. However, vboxmanage is not working correctly.
#ports:
#  - 8080
#  - 8081
#healthChecks:
#  pings:
    # I use localhost here as I'm using Boot2 Docker. If you use Linux is a multi-host set-up, then you can use
    # __CONTAINER.IP__
    #- url: http://__CONTAINER.IP__:8080
    #- url: http://localhost:8080
    #  timeout: 60000
tag: tyec/${project.artifactId}:${project.version}
